---
  - name: Download and install Metricbeat
    hosts: webservers
    remote_user: ansible
    become: true
    tasks:

    - name: download Metricbeat
      command: curl -L -O https://artifacts.elastic.co/downloads/beats/metricbeat/metricbeat-7.6.1-amd64.deb

    - name: install Metricbeat
      command: sudo dpkg -i metricbeat-7.6.1-amd64.deb

    - name: drop in the metricbeat.yml
      copy:
        src: /etc/ansible/files/metricbeat/metricbeat.yml
        dest: /etc/metricbeat/metricbeat.yml

    - name: enable metricbeat modules enable docker 
      command: metricbeat modules enable docker

    - name: setup metricbeat
      command: metricbeat setup

    - name: start metricbeat service
      command: service metricbeat start

  # Use command module
    - name: Increase virtual memory
      command: sysctl -w vm.max_map_count=262144

   # Use shell module
    - name: Increase virtual memory on restart
      shell: echo "vm.max_map_count=262144" >> /etc/sysctl.conf
